CREATE TABLE funds (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	fname TEXT NOT NULL,
	lname TEXT NOT NULL
);

CREATE TABLE user_funds (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	fk_user INTEGER NOT NULL,
	fk_fund INTEGER NOT NULL,

    FOREIGN KEY(fk_user) REFERENCES users(id),
    FOREIGN KEY(fk_fund) REFERENCES funds(id)
);

CREATE TABLE investments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	fk_user INTEGER NOT NULL,
	fk_fund INTEGER NOT NULL,
    amount DECIMAL NOT NULL,

    FOREIGN KEY(fk_user) REFERENCES users(id),
    FOREIGN KEY(fk_fund) REFERENCES funds(id)
);

