CREATE TABLE fund (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	fname TEXT NOT NULL,
	lname TEXT NOT NULL
);

CREATE TABLE user_fund (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	fk_user INTEGER NOT NULL,
	fk_fund INTEGER NOT NULL,

    FOREIGN KEY(fk_user) REFERENCES users(id),
    FOREIGN KEY(fk_fund) REFERENCES funds(id)
);

CREATE TABLE investment (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	fk_user INTEGER NOT NULL,
	fk_fund INTEGER NOT NULL,
    amount DECIMAL NOT NULL,

    FOREIGN KEY(fk_user) REFERENCES users(id),
    FOREIGN KEY(fk_fund) REFERENCES funds(id)
);

